---
title: "Apresentação projeto 1"
format: revealjs
---

## Automoveis a combustão e suas consequencias

Na sociedade moderna, a emissão de poluentes e derivados de combustiveis fosseis advindas de veiculos a combustão, sem duvidas, são um dos desafios da modernidade. As consequências do uso em larga escala dessas fontes de energia, já causam impactos significativos e preocupantes em nossa sociedade, principalmente em grandes centros ubarnos! Os principais impactos são a poluição ambiental, chuvas acidas, poluição do ar e a emissão de gases de efeito estufa, além dos problemas causados por erro humano como, vazamento de petroleo e oléo em navios, contaminando os mares e oceanos tornando a area contaminada um lugar inóspito a vida. Esses problemas são bem evidenciados na segunda edição do relatório ["Do Berço ao Túmulo: o impacto dos combustíveis fósseis na saúde"] produzido pela Global Climate & Health Alliance, uma coalização internacional que busca combater as mudanças climáticas e atingir melhorias na da área de saúde publica. No Brasil, O Proconve (Programa de Controle da Poluição do Ar por Veículos Automotores) criado em 1986, lei criada com o objetivo de diminuir a poluição veicular completou recentemente completou 40 anos e seus impactos são extremamente positivos. O nível de emissão de monóxido de carbono por quilômetro rodado chegava a 54 g/km por veiculo e se considerar os 13 milhoes de veiculos da época, os numeros chegavam em 702 kg do poluente para um unico veiculo cerca 9.126 mill toneladas para o total da frota. Atualmente, o nível de emissão está em cerca de 0,4 g/km por km rodado, o que representa uma redução superior a 98% em relação ao início da implementação do programa para um unico veiculo, e se considerarmos a frota atual de 129 milhões de veículos, um veiculo polui cerca de 5,2 kg em um ano e toda frota cerca de (670,8 mil toneladas) uma redução de pelo menos 92%, dados do [Ibama](https://www.gov.br/ibama/pt-br/assuntos/noticias/2026/pioneiro-na-america-latina-programa-de-controle-da-poluicao-veicular-completa-40-anos). E para que fosse possivel essas reduções, os carros foram se modificando com o passar dos anos, uma mudança dessa magnitude evidentemente não veio pela boa vontade das empresas. Uma das imposições, foi a implementação dos catalisadores, a principal tarefa do catalisador é transformar três dos principais poluentes liberados pelo escapamento em substâncias menos prejudiciais ao planeta, no que diz respeito ao que estamos analizando, o monóxido de carbono é um gás tóxico. O catalisador automotivo converte o CO em dióxido de carbono (CO2), um gás que, embora seja poluente, não é tóxico da mesma forma que o monóxido de carbono. E isso somente já significa uma melhora na qualidade do ar respirado nas cidades, essa solução de transformação de CO em CO2 tira o problema do ar respirado e antecipa o que aconteceria inevitalmente, a transformação de CO em CO2, após a reação com o oxigênio, proporcionando assim uma melhoria qualitativa do ar respirado nas cidades. Outras soluções foram implementadas com o passar dos anos, como o uso da injeção direta de combustivel,que causa a do consumo de combustivel e da da emissão de CO2, entre outros avanços como a melhoria da qualidade do combustivel e adesão ao etanol, o uso do etanol parte da gasolina, e do biodiesel ao diesel. Essas mudanças representam melhorias incomparáveis ao que estavam presentes anteriores ao Proconve. Nesse cenário de necessidade de renovação energetica limpa no Brasil, o [Etanol](https://www.raizen.com.br/blog/etanol) (um biocombustível de matéria-prima vegetal, produzido por meio da fermentação do amido ou de outros açúcares, de origem vegetal, se destaca por ser um combustivel sustentável, renovável e pouco poluente em comparação com os combustiveis fosseis) une a necessidade por energias renovaveis e menos poluentes com a capacidade de produção do etanol brasileiro. Vale lembrar que diferente dos combustiveis fosseis que tem uma finitude, o etanol é renovavel e também uma fonte de energia mais limpa. Isso porque sua produção emite até 80% menos de gases de efeito estufa (GEE) - como dióxido de carbono (CO2), gás metano (CH4) e óxido nitroso (NO2), quando comparado à gasolina e o oléo diesel, para essa analise, o foco de emissão de poluentes estara voltado para o CO2.

## O foco da análise exploratória (EDA) na base de dados do INMETRO, o PBEV2026 (Programa Brasileiro de Etiquetagem Veicular)


## Referencias

<https://www.cetesb.sp.gov.br/cetesb/qualidade_ambiental/emissao_veicular> <https://www.cetesb.sp.gov.br/cetesb/qualidade_ambiental/emissao_veicular/proconve> <https://www.raizen.com.br/blog/etanol> <https://www.epe.gov.br/sites-pt/publicacoes-dados-abertos/publicacoes/PublicacoesArquivos/publicacao-250/topico-304/EPE%20-%202%C2%BA%20Biocombust%C3%ADveis%20x%20MDL%5B1%5D.pdf> <https://observatoriodopetroleo.org/conheca-alguns-impactos-ambientais-causados-pelo-uso-de-combustiveis-fosseis/> <https://sunne.com.br/blog/saiba-os-impactos-dos-combustiveis-fosseis/> <https://ric.cps.sp.gov.br/bitstream/123456789/6774/1/tecnicoemqu%C3%ADmica_2021_2_marcosoliveira_impactoscausadospelousodoscombust%C3%ADveisf%C3%B3sseis.pdf> <https://antigo.mma.gov.br/mma-em-numeros/emissoes-veiculares.html> <https://secom.ufg.br/n/33974-catastrofe-ambiental-petroleo-no-mar> <https://anfavea.com.br/site/o-que-e-o-proconve/> <https://dadosabertos.ibama.gov.br/dataset/emissoes-de-poluentes-atmosfericos> <https://www.gov.br/ibama/pt-br/assuntos/noticias/2026/pioneiro-na-america-latina-programa-de-controle-da-poluicao-veicular-completa-40-anos> <https://professor.ufop.br/sites/default/files/victor/files/reducao_com_monoxido_de_carbono_-_parte_1.pdf> <https://totalenergies.com.br/catalisador-automotivo-o-que-e-e-como-funciona> <https://blog.simplusbr.com/injecao-direta-de-combustivel/>
